# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 196b78a95f7d6a42b18018f4e05247fcc2841e569f25bc48b16c35f7054bebeb9e9e0b906df1b8e8147db6a41e161c7f1e0750476fb39a7e97d9c04825923fb1

test:
  secret_key_base: d0975a6becf29e1dd81b0cabd1d7e2a1b0a4b9bcac926dde1cbc928fff6d9c10fbaeab0da36ce01b11421036176158823bd0ee44796c4d219c57ba798e138f05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
